# Maya Sosa, Midterm, October 5th 2021

Problem 1:

In [5]:
import numpy as np

Problem 2:

In [277]:
print('Select two cities from the following list as a start and endpoint to your trip.')

city_list = ['Atlanta', 'Baltimore', 'Boston', 'Charlotte', 'Dallas', 'Denver', 'Miami', 'Minneapolis', 'Orlando', 'Sacramento', 'Tampa', 'Washington']
print('Cities to choose from:', city_list)

Select two cities from the following list as a start and endpoint to your trip.
Cities to choose from: ['Atlanta', 'Baltimore', 'Boston', 'Charlotte', 'Dallas', 'Denver', 'Miami', 'Minneapolis', 'Orlando', 'Sacramento', 'Tampa', 'Washington']


In [278]:
print('Please input a start city from the list in the first box and hit enter, then input a destination city from the list in the second box and hit enter (Remember to capitalize the first letter!):')
start_city = input()
target_city = input()

    
if start_city not in city_list:
    print( 'Sorry, the city', start_city, 'is not in the list, please input a city from the list')
    start_city = input()
    
if target_city not in city_list:
    print( 'Sorry, the city', target_city, 'is not in the list, please input a city from the list')
    target_city = input()
    
    
print('Great! You have chosen to travel from', start_city, 'to', target_city)


Please input a start city from the list in the first box and hit enter, then input a destination city from the list in the second box and hit enter (Remember to capitalize the first letter!):
Paris
Orlando
Sorry, the city Paris is not in the list, please input a city from the list
Atlanta
Great! You have chosen to travel from Atlanta to Orlando


Problem 3:

In [6]:
travel_data = np.loadtxt('distances_midterm.dat', comments = '#')

In [280]:
print(travel_data)

[[   0.  678. 1094.  245.  782. 1402.  662. 1127.  438. 2467.  467.  638.]
 [ 678.    0.  400.  422. 1366. 1633. 1103. 1109.  983. 2730.  941.   39.]
 [1094.  400.    0.  839. 1761. 1969. 1497. 1390. 1381. 3008. 1341.  439.]
 [ 245.  422.  839.    0. 1026. 1562.  735. 1180.  524. 2676.  580.  399.]
 [ 782. 1366. 1761. 1026.    0.  785. 1313.  991. 1092. 1726. 1107. 1328.]
 [1402. 1633. 1969. 1562.  785.    0. 2064.  914. 1843. 1162. 1857. 1661.]
 [ 662. 1103. 1497.  735. 1313. 2064.    0. 1773.  237. 3039.  270. 1158.]
 [1127. 1109. 1390. 1180.  991.  914. 1773.    0. 1568. 1887. 1583. 1108.]
 [ 438.  983. 1381.  524. 1092. 1843.  237. 1568.    0. 2810.   84.  846.]
 [2467. 2730. 3008. 2676. 1726. 1162. 3039. 1887. 2810.    0. 2832. 2728.]
 [ 467.  941. 1341.  580. 1107. 1857.  270. 1583.   84. 2832.    0.  903.]
 [ 638.   39.  439.  390. 1328. 1661. 1158. 1108.  846. 2728.  903.    0.]]


In [281]:
for j in city_list:
    if j == start_city:
        first_city = city_list.index(j)
        

for i in city_list:
    if i == target_city:
        second_city = city_list.index(i)
        
        
x = travel_data[first_city, second_city]

print('You will travel', x, 'miles between', start_city, 'and', target_city)

You will travel 438.0 miles between Atlanta and Orlando


In [282]:
#Assuming average travel speed is 75mph

days = (x / 75) / 24
travel_time_days = int(days)

hours = (x / 75) - (travel_time_days * 24)
travel_time_hours = int(hours)

minutes = ((x / 75) * 60) - (travel_time_hours * 60)
travel_time_minutes = int(minutes)


print('Your trip from', start_city, 'to', target_city, 'will take', travel_time_days, 'day(s)', travel_time_hours, 'hour(s) and', travel_time_minutes, 'minute(s).')

Your trip from Atlanta to Orlando will take 0 day(s) 5 hour(s) and 50 minute(s).


In [284]:
def navigation(start_city, target_city):
    """Given a starting city from list and a destination city from the list, function returns the distance between the two
    cities as well as the amount of time in days, hours, and minutes it takes to get there (assuming an avg speed of 75mph)
    Inputs: start_city and target_city
    Outputs: distance and time to get there (days/hours/minutes)"""
    
    city_list = ['Atlanta', 'Baltimore', 'Boston', 'Charlotte', 'Dallas', 'Denver', 'Miami', 'Minneapolis', 'Orlando', 'Sacramento', 'Tampa', 'Washington']
    
    for j in city_list:
        if j == start_city:
            first_city = city_list.index(j)
        

    for i in city_list:
        if i == target_city:
            second_city = city_list.index(i)
        
        
    x = travel_data[first_city, second_city]


    days = (x / 75) / 24
    travel_time_days = int(days)

    hours = (x / 75) - (travel_time_days * 24)
    travel_time_hours = int(hours)

    minutes = ((x / 75) * 60) - (travel_time_hours * 60) - (travel_time_days * 60 * 24 )
    travel_time_minutes = int(minutes)

    return(print('Your trip from', start_city, 'to', target_city, 'is', x, 'miles and will take you a total of', travel_time_days, 'day(s)', travel_time_hours, 'hour(s) and', travel_time_minutes, 'minute(s).'))

In [285]:
navigation('Tampa', 'Orlando')

Your trip from Tampa to Orlando is 84.0 miles and will take you a total of 0 day(s) 1 hour(s) and 7 minute(s).


Problem 4:

In [286]:
def nav_pitstop(start_city, pitstop_city, target_city):
    """Given a starting city, pitstop city from list and a destination city from the list, function returns the distance between the two
    cities as well as the amount of time in days, hours, and minutes it takes to get there (assuming an avg speed of 75mph)
    Inputs: start_city, pitstop_city, and target_city
    Outputs: Distance and time to get from city to city (days/hours/minutes)"""
    
    city_list = ['Atlanta', 'Baltimore', 'Boston', 'Charlotte', 'Dallas', 'Denver', 'Miami', 'Minneapolis', 'Orlando', 'Sacramento', 'Tampa', 'Washington']
    
    for j in city_list:
        if j == start_city:
            first_city = city_list.index(j)
            
    for k in city_list:
        if k == pitstop_city:
            between_city = city_list.index(k)
        
    for i in city_list:
        if i == target_city:
            second_city = city_list.index(i)
        
        
    x1 = travel_data[first_city, between_city]
    x2 = travel_data[between_city, second_city]
    

    #Time between start and pitstop city
    days1 = (x1 / 75) / 24
    travel_time_days1 = int(days1)

    hours1 = (x1 / 75) - (travel_time_days1 * 24)
    travel_time_hours1 = int(hours1)

    minutes1 = ((x1 / 75) * 60) - (travel_time_hours1 * 60) - (travel_time_days1 * 60 * 24 )
    travel_time_minutes1 = int(minutes1)
    
    
    #Time between pitstop city and target city
    days2 = (x2 / 75) / 24
    travel_time_days2 = int(days2)

    hours2 = (x2 / 75) - (travel_time_days2 * 24)
    travel_time_hours2 = int(hours2)

    minutes2 = ((x2 / 75) * 60) - (travel_time_hours2 * 60) - (travel_time_days2 * 60 * 24 )
    travel_time_minutes2 = int(minutes2)

    return(print('Your trip from', start_city, 'to', pitstop_city, 'is', x1, 'miles and will take you a total of', travel_time_days1, 'day(s)', travel_time_hours1, 'hour(s) and', travel_time_minutes1, 'minute(s) while your trip from', pitstop_city, 'to', target_city, 'is', x2, 'miles and will take you a total of', travel_time_days2, 'day(s)', travel_time_hours2, 'hour(s) and', travel_time_minutes2, 'minute(s).'))

In [287]:
nav_pitstop('Boston', 'Denver', 'Sacramento')

Your trip from Boston to Denver is 1969.0 miles and will take you a total of 1 day(s) 2 hour(s) and 15 minute(s) while your trip from Denver to Sacramento is 1162.0 miles and will take you a total of 0 day(s) 15 hour(s) and 29 minute(s).


In [288]:
print('Please choose three cities from the following list', city_list)

print('Input a starting city from the list in the first box and hit enter, then input a pitstop city and lastly input destination city (Remember to capitalize the first letters!):')
start_city = input()
pitstop_city = input()
target_city = input()

    
if start_city not in city_list:
    print( 'Sorry, the city', start_city, 'is not in the list, please input a city from the list')
    start_city = input()
    
if pitstop_city not in city_list:
    print( 'Sorry, the city', pitstop_city, 'is not in the list, please input a city from the list')
    pitstop_city = input()
    
if target_city not in city_list:
    print( 'Sorry, the city', target_city, 'is not in the list, please input a city from the list')
    target_city = input()
    
    
nav_pitstop(start_city, pitstop_city, target_city)

Please choose three cities from the following list ['Atlanta', 'Baltimore', 'Boston', 'Charlotte', 'Dallas', 'Denver', 'Miami', 'Minneapolis', 'Orlando', 'Sacramento', 'Tampa', 'Washington']
Input a starting city from the list in the first box and hit enter, then input a pitstop city and lastly input destination city (Remember to capitalize the first letters!):
Boston
Denver
Sacramento
Your trip from Boston to Denver is 1969.0 miles and will take you a total of 1 day(s) 2 hour(s) and 15 minute(s) while your trip from Denver to Sacramento is 1162.0 miles and will take you a total of 0 day(s) 15 hour(s) and 29 minute(s).


In [9]:
import math
#Using it in next section to round gas trips needed up

In [290]:
#Car has 24.9mpg and holds 16 gallons

for j in city_list:
        if j == start_city:
            first_city = city_list.index(j)
            
for k in city_list:
     if k == pitstop_city:
            between_city = city_list.index(k)  

for i in city_list:
    if i == target_city:
        second_city = city_list.index(i)
        
        
x1 = travel_data[first_city, between_city]
x2 = travel_data[between_city, second_city]
    
pitstop1 = math.ceil((x1 / 24.9) /16)
pitstop2 = math.ceil((x2 / 24.9) /16)

print('From', start_city, 'to', pitstop_city, 'you will need to make about', pitstop1 ,'stop(s) for gas.')
print('From', pitstop_city, 'to', target_city, 'you will need to make about', pitstop2 , 'stop(s) for gas.')


#$2.40 per gallon and assuming they fill their tank at each stop

gas_cost = 2.4 * 16 * (pitstop1 + pitstop2)
print('You can estimate to spend ~ $', gas_cost, 'in gas')


From Boston to Denver you will need to make about 5 stop(s) for gas.
From Denver to Sacramento you will need to make about 3 stop(s) for gas.
You can estimate to spend ~ $ 307.2 in gas


Problem 5:

In [302]:
print('Please input a start city from the list in the first box and hit enter, then input a destination city from the list in the second box and hit enter (Remember to capitalize the first letter!):')
print('Cities to choose from:', city_list)
start_city = input()
target_city = input()

Please input a start city from the list in the first box and hit enter, then input a destination city from the list in the second box and hit enter (Remember to capitalize the first letter!):
Cities to choose from: ['Atlanta', 'Baltimore', 'Boston', 'Charlotte', 'Dallas', 'Denver', 'Miami', 'Minneapolis', 'Orlando', 'Sacramento', 'Tampa', 'Washington']
Baltimore
Orlando


In [303]:
for j in city_list:
    if j == start_city:
        first_city = city_list.index(j)

for i in city_list:
    if i == target_city:
        second_city = city_list.index(i)
        
list1 = travel_data[first_city,]
list2 = travel_data[second_city,]

temp_min = 99999
                
list = list1 + list2

for l in list:
    if l < temp_min and l != list[first_city]:
        temp_min = l
        
            
f = np.where(list == temp_min)

pitstop_city = city_list[f[0][0]]


print('Fastest pitstop from', start_city, 'to', target_city, 'is in', pitstop_city  )   
print('Total distance of trip:', temp_min,'miles')

#Problem 5B number 1 and for #2 got Washington


Fastest pitstop from Baltimore to Orlando is in Washington
Total distance of trip: 885.0 miles


In [304]:
for j in city_list:
        if j == start_city:
            first_city = city_list.index(j)
            
for k in city_list:
     if k == pitstop_city:
            between_city = city_list.index(k)  

for i in city_list:
    if i == target_city:
        second_city = city_list.index(i)

x1 = travel_data[first_city, between_city]
x2 = travel_data[between_city, second_city]
    
pitstop1 = math.ceil((x1 / 24.9) /16)
pitstop2 = math.ceil((x2 / 24.9) /16)

print('From', start_city, 'to', pitstop_city, 'you will need to make about', pitstop1 ,'stop(s) for gas.')
print('From', pitstop_city, 'to', target_city, 'you will need to make about', pitstop2 , 'stop(s) for gas.')


#$2.40 per gallon

gas_cost = 2.4 * 16 * (pitstop1 + pitstop2)
print('You can estimate to spend ~ $', gas_cost,'in gas')

From Baltimore to Washington you will need to make about 1 stop(s) for gas.
From Washington to Orlando you will need to make about 3 stop(s) for gas.
You can estimate to spend ~ $ 153.6 in gas


Done!! Not sure if we had to do this but I created another function based on problem 5 below 

In [7]:
def trip_planner(start_city, target_city):
    """Given a starting and destination city from the list, function finds city from list to create a pitstop in that creates 
    a trip of the shortest distance and informs user of what that pitstop city is and how long the total trip will be.
    Function also informs user of how many gas stops they will need to make on each leg of the trip and total price of those gas stops.
    Inputs: start_city and target_city
    Outputs: Pitstop City, Distance (mi) of total trip, Number of gas stops needed on each leg, and total price of gas"""
    
    city_list = ['Atlanta', 'Baltimore', 'Boston', 'Charlotte', 'Dallas', 'Denver', 'Miami', 'Minneapolis', 'Orlando', 'Sacramento', 'Tampa', 'Washington']
    
   #Finding Pitstop City
    for j in city_list:
        if j == start_city:
            first_city = city_list.index(j)

    for i in city_list:
        if i == target_city:
            second_city = city_list.index(i)
        
    list1 = travel_data[first_city,]
    list2 = travel_data[second_city,]

    temp_min = 99999
                
    list = list1 + list2

    for l in list:
        if l < temp_min and l != list[first_city]: #Makes sure straight trip A to B is not included
            temp_min = l
        
    f = np.where(list == temp_min)

    pitstop_city = city_list[f[0][0]]
    
    #Finding gas stops/cost
    for k in city_list:
        if k == pitstop_city:
            between_city = city_list.index(k) 
    
    x1 = travel_data[first_city, between_city]
    x2 = travel_data[between_city, second_city]
    
    pitstop1 = math.ceil((x1 / 24.9) /16)
    pitstop2 = math.ceil((x2 / 24.9) /16)

    gas_cost = 2.4 * 16 * (pitstop1 + pitstop2)
    
    #Finding time between start city and pitstop city
    days1 = (x1 / 75) / 24
    travel_time_days1 = int(days1)

    hours1 = (x1 / 75) - (travel_time_days1 * 24)
    travel_time_hours1 = int(hours1)

    minutes1 = ((x1 / 75) * 60) - (travel_time_hours1 * 60) - (travel_time_days1 * 60 * 24 )
    travel_time_minutes1 = int(minutes1)
    
    
    #Time between pitstop city and target city
    days2 = (x2 / 75) / 24
    travel_time_days2 = int(days2)

    hours2 = (x2 / 75) - (travel_time_days2 * 24)
    travel_time_hours2 = int(hours2)

    minutes2 = ((x2 / 75) * 60) - (travel_time_hours2 * 60) - (travel_time_days2 * 60 * 24 )
    travel_time_minutes2 = int(minutes2)
    
    #Adding them together for total time
    travel_time_days = travel_time_days1 + travel_time_days2
    travel_time_hours = travel_time_hours1 + travel_time_hours2
    travel_time_minutes = travel_time_minutes1 + travel_time_minutes2

    return(print('Fastest pitstop from', start_city, 'to', target_city, 'is in', pitstop_city, ', making the total distance of trip', temp_min,'miles. It will take about', travel_time_days, 'day(s)', travel_time_hours, 'hour(s) and', travel_time_minutes, 'minute(s) to complete the trip.', 
                 'From', start_city, 'to', pitstop_city, 'you will need to make about', pitstop1 ,'stop(s) for gas.', 
                 'From', pitstop_city, 'to', target_city, 'you will need to make about', pitstop2 , 'stop(s) for gas.',
                 'You can estimate to spend ~ $', gas_cost,'in gas.'))

In [336]:
trip_planner('Miami', 'Tampa')

Fastest pitstop from Miami to Tampa is in Orlando , making the total distance of trip 321.0 miles. It will take about 0 day(s) 4 hour(s) and 16 minute(s) to complete the trip. From Miami to Orlando you will need to make about 1 stop(s) for gas. From Orlando to Tampa you will need to make about 1 stop(s) for gas. You can estimate to spend ~ $ 76.8 in gas.


In [10]:
trip_planner('Baltimore', 'Minneapolis')

Fastest pitstop from Baltimore to Minneapolis is in Washington , making the total distance of trip 1147.0 miles. It will take about 0 day(s) 14 hour(s) and 77 minute(s) to complete the trip. From Baltimore to Washington you will need to make about 1 stop(s) for gas. From Washington to Minneapolis you will need to make about 3 stop(s) for gas. You can estimate to spend ~ $ 153.6 in gas.
