# Maya Sosa, Midterm, October 5th 2021

Problem 1:

In [171]:
import numpy as np

Problem 2:

In [189]:
print('Select two cities from the following list as a start and endpoint to your trip.')

city_list = ['Atlanta', 'Baltimore', 'Boston', 'Charlotte', 'Dallas', 'Denver', 'Miami', 'Minneapolis', 'Orlando', 'Sacramento', 'Tampa', 'Washington']
print('Cities to choose from:', city_list)

Select two cities from the following list as a start and endpoint to your trip.
Cities to choose from: ['Atlanta', 'Baltimore', 'Boston', 'Charlotte', 'Dallas', 'Denver', 'Miami', 'Minneapolis', 'Orlando', 'Sacramento', 'Tampa', 'Washington']


In [58]:
print('Please input a start city from the list in the first box and hit enter, then input a destination city from the list in the second box and hit enter (Remember to capitalize the first letter!):')
start_city = input()
target_city = input()

    
if start_city not in city_list:
    print( 'Sorry, the city', start_city, 'is not in the list, please input a city from the list')
    start_city = input()
    
if target_city not in city_list:
    print( 'Sorry, the city', target_city, 'is not in the list, please input a city from the list')
    target_city = input()
    
    
print('Great! You have chosen to travel from', start_city, 'to', target_city)


Please input a start city from the list in the first box and hit enter, then input a destination city from the list in the second box and hit enter (Remember to capitalize the first letter!):
tampa
Orlando
Sorry, the city tampa is not in the list, please input a city from the list
Tampa
Great! You have chosen to travel from Tampa to Orlando


Problem 3:

In [30]:
travel_data = np.loadtxt('distances_midterm.dat', comments = '#')

In [31]:
print(travel_data)

[[   0.  678. 1094.  245.  782. 1402.  662. 1127.  438. 2467.  467.  638.]
 [ 678.    0.  400.  422. 1366. 1633. 1103. 1109.  983. 2730.  941.   39.]
 [1094.  400.    0.  839. 1761. 1969. 1497. 1390. 1381. 3008. 1341.  439.]
 [ 245.  422.  839.    0. 1026. 1562.  735. 1180.  524. 2676.  580.  399.]
 [ 782. 1366. 1761. 1026.    0.  785. 1313.  991. 1092. 1726. 1107. 1328.]
 [1402. 1633. 1969. 1562.  785.    0. 2064.  914. 1843. 1162. 1857. 1661.]
 [ 662. 1103. 1497.  735. 1313. 2064.    0. 1773.  237. 3039.  270. 1158.]
 [1127. 1109. 1390. 1180.  991.  914. 1773.    0. 1568. 1887. 1583. 1108.]
 [ 438.  983. 1381.  524. 1092. 1843.  237. 1568.    0. 2810.   84.  846.]
 [2467. 2730. 3008. 2676. 1726. 1162. 3039. 1887. 2810.    0. 2832. 2728.]
 [ 467.  941. 1341.  580. 1107. 1857.  270. 1583.   84. 2832.    0.  903.]
 [ 638.   39.  439.  390. 1328. 1661. 1158. 1108.  846. 2728.  903.    0.]]


In [59]:
for j in city_list:
    if j == start_city:
        first_city = city_list.index(j)
        

for i in city_list:
    if i == target_city:
        second_city = city_list.index(i)
        
        
x = travel_data[first_city, second_city]

print('You will travel', x, 'miles between', start_city, 'and', target_city)

You will travel 84.0 miles between Tampa and Orlando


In [62]:
#Assuming avergae travel speed is 75mph

days = (x / 75) / 24
travel_time_days = int(days)

hours = (x / 75) - (travel_time_days * 24)
travel_time_hours = int(hours)

minutes = ((x / 75) * 60) - (travel_time_hours * 60)
travel_time_minutes = int(minutes)


print('Your trip from', start_city, 'to', target_city, 'will take', travel_time_days, 'day(s)', travel_time_hours, 'hour(s) and', travel_time_minutes, 'minute(s).')

Your trip from Tampa to Orlando will take 0 day(s) 1 hour(s) and 7 minute(s).


In [88]:
def navigation(start_city, target_city):
    """Given a starting city from list and a destination city from the list, function returns the distance between the two
    cities as well as the amount of time in days, hours, and minutes it takes to get there (assuming an avg speed of 75mph)
    Inputs: start_city and target_city
    Outputs: distance and time to get there (days/hours/minutes)"""
    
    city_list = ['Atlanta', 'Baltimore', 'Boston', 'Charlotte', 'Dallas', 'Denver', 'Miami', 'Minneapolis', 'Orlando', 'Sacramento', 'Tampa', 'Washington']
    
    for j in city_list:
        if j == start_city:
            first_city = city_list.index(j)
        

    for i in city_list:
        if i == target_city:
            second_city = city_list.index(i)
        
        
    x = travel_data[first_city, second_city]


    days = (x / 75) / 24
    travel_time_days = int(days)

    hours = (x / 75) - (travel_time_days * 24)
    travel_time_hours = int(hours)

    minutes = ((x / 75) * 60) - (travel_time_hours * 60) - (travel_time_days * 60 * 24 )
    travel_time_minutes = int(minutes)

    return(print('Your trip from', start_city, 'to', target_city, 'is', x, 'miles and will take you a total of', travel_time_days, 'day(s)', travel_time_hours, 'hour(s) and', travel_time_minutes, 'minute(s).'))

In [89]:
navigation('Atlanta', 'Miami')

Your trip from Atlanta to Miami is 662.0 miles and will take you a total of 0 day(s) 8 hour(s) and 49 minute(s).


Problem 4:

In [90]:
def nav_pitstop(start_city, pitstop_city, target_city):
    """Given a starting city, pitstop city from list and a destination city from the list, function returns the distance between the two
    cities as well as the amount of time in days, hours, and minutes it takes to get there (assuming an avg speed of 75mph)
    Inputs: start_city, pitstop_city, and target_city
    Outputs: Distance and time to get from city to city (days/hours/minutes)"""
    
    city_list = ['Atlanta', 'Baltimore', 'Boston', 'Charlotte', 'Dallas', 'Denver', 'Miami', 'Minneapolis', 'Orlando', 'Sacramento', 'Tampa', 'Washington']
    
    for j in city_list:
        if j == start_city:
            first_city = city_list.index(j)
            
    for k in city_list:
        if k == pitstop_city:
            between_city = city_list.index(k)
        
    for i in city_list:
        if i == target_city:
            second_city = city_list.index(i)
        
        
    x1 = travel_data[first_city, between_city]
    x2 = travel_data[between_city, second_city]
    

    #Time between start and pitstop city
    days1 = (x1 / 75) / 24
    travel_time_days1 = int(days1)

    hours1 = (x1 / 75) - (travel_time_days1 * 24)
    travel_time_hours1 = int(hours1)

    minutes1 = ((x1 / 75) * 60) - (travel_time_hours1 * 60) - (travel_time_days1 * 60 * 24 )
    travel_time_minutes1 = int(minutes1)
    
    
    #Time between pitstop city and target city
    days2 = (x2 / 75) / 24
    travel_time_days2 = int(days2)

    hours2 = (x2 / 75) - (travel_time_days2 * 24)
    travel_time_hours2 = int(hours2)

    minutes2 = ((x2 / 75) * 60) - (travel_time_hours2 * 60) - (travel_time_days2 * 60 * 24 )
    travel_time_minutes2 = int(minutes2)

    return(print('Your trip from', start_city, 'to', pitstop_city, 'is', x1, 'miles and will take you a total of', travel_time_days1, 'day(s)', travel_time_hours1, 'hour(s) and', travel_time_minutes1, 'minute(s) while your trip from', pitstop_city, 'to', target_city, 'is', x2, 'miles and will take you a total of', travel_time_days2, 'day(s)', travel_time_hours2, 'hour(s) and', travel_time_minutes2, 'minute(s).'))

In [91]:
nav_pitstop('Boston', 'Denver', 'Sacramento')

Your trip from Boston to Denver is 1969.0 miles and will take you a total of 1 day(s) 2 hour(s) and 15 minute(s) while your trip from Denver to Sacramento is 1162.0 miles and will take you a total of 0 day(s) 15 hour(s) and 29 minute(s).


In [93]:
print('Please choose three cities from the following list', city_list)

print('Input a starting city from the list in the first box and hit enter, then input a pitstop city and lastly input destination city (Remember to capitalize the first letters!):')
start_city = input()
pitstop_city = input()
target_city = input()

    
if start_city not in city_list:
    print( 'Sorry, the city', start_city, 'is not in the list, please input a city from the list')
    start_city = input()
    
if pitstop_city not in city_list:
    print( 'Sorry, the city', pitstop_city, 'is not in the list, please input a city from the list')
    pitstop_city = input()
    
if target_city not in city_list:
    print( 'Sorry, the city', target_city, 'is not in the list, please input a city from the list')
    target_city = input()
    
    
nav_pitstop(start_city, pitstop_city, target_city)

Please choose three cities from the following list ['Atlanta', 'Baltimore', 'Boston', 'Charlotte', 'Dallas', 'Denver', 'Miami', 'Minneapolis', 'Orlando', 'Sacramento', 'Tampa', 'Washington']
Input a starting city from the list in the first box and hit enter, then input a pitstop city and lastly input destination city (Remember to capitalize the first letters!):
Boston
Denver
Sacramento
Your trip from Boston to Denver is 1969.0 miles and will take you a total of 1 day(s) 2 hour(s) and 15 minute(s) while your trip from Denver to Sacramento is 1162.0 miles and will take you a total of 0 day(s) 15 hour(s) and 29 minute(s).


In [96]:
import math
#Using it in next section to round gas trips needed up

In [102]:
#Car has 24.9mpg and holds 16 gallons

for j in city_list:
        if j == start_city:
            first_city = city_list.index(j)
            
for k in city_list:
     if k == pitstop_city:
            between_city = city_list.index(k)  

for i in city_list:
    if i == target_city:
        second_city = city_list.index(i)
        
        
x1 = travel_data[first_city, between_city]
x2 = travel_data[between_city, second_city]
    
pitstop1 = math.ceil((x1 / 24.9) /16)
pitstop2 = math.ceil((x2 / 24.9) /16)

print('From', start_city, 'to', pitstop_city, 'you will need to make about', pitstop1 ,'stops for gas.')
print('From', pitstop_city, 'to', target_city, 'you will need to make about', pitstop2 , 'stops for gas.')


#$2.40 per gallon

gas_cost = 2.4 * 16 * 8
print('Between the 8 stops for gas you can estimate to spend ~ $', gas_cost)


From Boston to Denver you will need to make about 5 stops for gas.
From Denver to Sacramento you will need to make about 3 stops for gas.
Between the 8 stops for gas you can estimate to spend ~ $ 307.2


Problem 5:

In [269]:
print('Please input a start city from the list in the first box and hit enter, then input a destination city from the list in the second box and hit enter (Remember to capitalize the first letter!):')
print('Cities to choose from:', city_list)
start_city = input()
target_city = input()

Please input a start city from the list in the first box and hit enter, then input a destination city from the list in the second box and hit enter (Remember to capitalize the first letter!):
Cities to choose from: ['Atlanta', 'Baltimore', 'Boston', 'Charlotte', 'Dallas', 'Denver', 'Miami', 'Minneapolis', 'Orlando', 'Sacramento', 'Tampa', 'Washington']
Baltimore
Orlando


In [270]:
for j in city_list:
    if j == start_city:
        first_city = city_list.index(j)

for i in city_list:
    if i == target_city:
        second_city = city_list.index(i)
        
list1 = travel_data[first_city,]
list2 = travel_data[second_city,]

temp_min = 99999
                
list = list1 + list2

for l in list:
    if l < temp_min and l != list[first_city]:
        temp_min = l
        
            
f = np.where(list == temp_min)

pit_city = city_list[f[0][0]]


print('Fastest pitstop from', start_city, 'to', target_city, 'is in', pit_city  )   
print('Total distance of trip:', temp_min,'miles')

#Problem 5B number 1 and for #2 got Washington


Fastest pitstop from Baltimore to Orlando is in Washington
Total distance of trip: 885.0 miles


In [ ]:
print('You will need to stop', ,'times for gas, which will come to a total of $', )